apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-app.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "springboot-app.selectorLabels" . | nindent 4 }}
