apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.springbootService.name }}
spec:
  selector:
    app: springboot-app  # Replace with the correct label for your Spring Boot app pods
  ports:
    - protocol: TCP
      port: {{ .Values.springbootService.port }}
      targetPort: {{ .Values.springbootService.targetPort }}
  type: {{ .Values.springbootService.type }}
